apiVersion: apps/v1
kind: Deployment
metadata:
  name: brule-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brule
  template:
    metadata:
      labels:
        app: brule
    spec:
      containers:
      - name: brule
        image: IMAGE_TAG
        ports:
        - containerPort: 80