apiVersion: v1
kind: Service
metadata:
  name: brule-service

spec:
  selector:
    app: brule

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80   # 👉 change if app uses 3000

  type: NodePort