name: CD - Deploy to Kubernetes

on:
  workflow_run:
    workflows: ["CI - Build & Push Docker"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Kubeconfig
      run: |
        kubectl config use-context minikube

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml

    - name: Force Rollout Restart
      run: |
        kubectl rollout restart deployment devops-app