name: CD-Deploy-K8s

on:
  workflow_run:
    workflows: ["CI - Build & Push 🐳"]
    types:
      - completed

env:
  DEPLOYMENT_NAME: brule-deployment
  CONTAINER_NAME: brule

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
    - name: Test Runner
      run: echo "CD TRIGGERED SUCCESSFULLY 🚀"

    - name: Check Cluster
      run: |
        kubectl cluster-info
        kubectl get nodes

    - name: Create Image Pull Secret
      run: |
        kubectl delete secret jfrog-secret --ignore-not-found
        kubectl create secret docker-registry jfrog-secret \
          --docker-server=${{ secrets.JFROG_REGISTRY }} \
          --docker-username=${{ secrets.JFROG_USERNAME }} \
          --docker-password=${{ secrets.JFROG_PASSWORD }} \
          --docker-email=dev@example.com

    - name: Apply Manifests
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml

    - name: Update Image
      run: |
        kubectl set image deployment/${{ env.DEPLOYMENT_NAME }} \
        ${{ env.CONTAINER_NAME }}=${{ secrets.JFROG_REGISTRY }}/brule-docker/brule:latest

    - name: Rollout Status
      run: |
        kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME }} --timeout=120s

    - name: Verify
      run: |
        kubectl get pods -o wide
        kubectl get svc