name: CI-CD Pipeline

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: Brule

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Generate Version
      run: |
        VERSION=v$(date +%s)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Docker Login
      run: |
        echo "${{ secrets.JFROG_PASSWORD }}" | docker login ${{ secrets.JFROG_REGISTRY }} \
        -u ${{ secrets.JFROG_USERNAME }} \
        --password-stdin

    - name: Build Image
      run: |
        docker build -t ${{ secrets.JFROG_REGISTRY }}/docker-trial/${{ env.IMAGE_NAME }}:${{ env.VERSION }} .

    - name: Push Image
      run: |
        docker push ${{ secrets.JFROG_REGISTRY }}/docker-trial/${{ env.IMAGE_NAME }}:${{ env.VERSION }}

    - name: Setup Kubeconfig
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig
        echo "KUBECONFIG=$PWD/kubeconfig" >> $GITHUB_ENV

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl set image deployment/myapp-deployment myapp=${{ secrets.JFROG_REGISTRY }}/docker-trial/${{ env.IMAGE_NAME }}:${{ env.VERSION }}

    - name: Check Rollout Status
      run: |
        kubectl rollout status deployment/myapp-deployment